/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Judge API Route - Evaluate agent trajectories
 */

import { Request, Response, Router } from 'express';
import { BedrockClient, ListInferenceProfilesCommand } from '@aws-sdk/client-bedrock';
import { fromNodeProviderChain } from '@aws-sdk/credential-providers';
import { evaluateTrajectory, parseBedrockError } from '@/server/services/bedrockService';
import { evaluateWithOpenAICompatible, parseOpenAICompatibleError } from '@/server/services/judgeService';
import { evaluateWithLiteLLM, parseLiteLLMError } from '@/server/services/litellmJudgeService';
import { evaluateWithClaudeCode, parseClaudeCodeError } from '@/server/services/claudeCodeJudgeService';
import { evaluateWithPi, parsePiError } from '@/server/services/piJudgeService';
import { evaluateWithPiAgenticTrace } from '@/server/services/piAgenticJudgeService';
import { evaluateWithAgenticJudge, parseAgenticJudgeError } from '@/server/services/agenticJudgeService';
import { loadConfigSync } from '@/lib/config/index';
import serverConfig from '@/server/config';
import { debug } from '@/lib/debug';
import { readEnv } from '@/lib/envCompat';
import { getStorageModule } from '@/server/adapters';
import { getDefaultEvaluator, getSystemEvaluatorById, isSystemEvaluatorId } from '@/server/prompts/evaluatorTemplates';
import type { Evaluator } from '@/types';

const router = Router();

/**
 * SSRF guard for model-discovery endpoints that forward a provider credential
 * (Anthropic API key, GitHub token) to an operator-configurable base URL.
 *
 * Both URLs are env-driven (`ANTHROPIC_BASE_URL`, `GITHUB_MODELS_URL`) so an
 * operator can point them at a proxy/gateway — but a credential must never be
 * sent to an arbitrary host. We require https and an allowlisted hostname
 * (the provider's own hosts, plus localhost for test proxies). Operators who
 * genuinely need a different host must opt in explicitly via
 * `AH_ALLOW_CUSTOM_MODEL_ENDPOINTS=1`, which is the documented escape hatch.
 *
 * Returns `null` when the URL is safe to call; otherwise an error string
 * (the caller returns 400 and does NOT forward the credential).
 */
function validateDiscoveryUrl(rawUrl: string, allowedHosts: string[]): string | null {
  let u: URL;
  try {
    u = new URL(rawUrl);
  } catch {
    return `Invalid discovery URL: ${rawUrl}`;
  }
  if (u.protocol !== 'https:' && u.hostname !== 'localhost' && u.hostname !== '127.0.0.1') {
    return `Refusing to send credential over non-https URL: ${u.protocol}//${u.hostname}`;
  }
  const optIn = readEnv('AH_ALLOW_CUSTOM_MODEL_ENDPOINTS', 'AGENT_HEALTH_ALLOW_CUSTOM_MODEL_ENDPOINTS') === '1';
  if (optIn) return null;
  const host = u.hostname.toLowerCase();
  const ok = allowedHosts.some(h => host === h || host.endsWith(`.${h}`)) || host === 'localhost' || host === '127.0.0.1';
  if (!ok) {
    return `Refusing to forward credential to non-allowlisted host '${host}'. ` +
      `Allowed: ${allowedHosts.join(', ')}. Set AH_ALLOW_CUSTOM_MODEL_ENDPOINTS=1 to override.`;
  }
  return null;
}

/**
 * Generate mock evaluation result for demo mode
 */
function generateMockEvaluation(trajectory: any[], expectedOutcomes: string[]): any {
  // Simulate realistic evaluation based on trajectory content
  const hasToolCalls = trajectory.some((step: any) => step.type === 'action' || step.toolName);
  const hasConclusion = trajectory.some((step: any) =>
    step.type === 'response' || (step.content && step.content.toLowerCase().includes('root cause'))
  );

  // Base accuracy on trajectory quality
  let accuracy = 0.7;
  if (hasToolCalls) accuracy += 0.1;
  if (hasConclusion) accuracy += 0.1;
  accuracy = Math.min(accuracy + (Math.random() * 0.1), 1.0);

  const passFailStatus = accuracy >= 0.7 ? 'passed' : 'failed';

  const accuracyPct = Math.round(accuracy * 100);
  return {
    passFailStatus,
    // Structured, machine-readable signal that this verdict is NOT real. The
    // CLI/UI can surface it, and unlike a footnote in the reasoning prose it
    // can't be lost (a real judge never sets `warning`).
    warning: 'MOCK_JUDGE: this score was produced by the demo/mock judge, not an LLM. Pin a real judge model (e.g. a Bedrock model) to get a real verdict.',
    metrics: {
      accuracy: accuracyPct,
      faithfulness: Math.round((accuracy - 0.05 + Math.random() * 0.1) * 100),
      latency_score: Math.round((0.8 + Math.random() * 0.2) * 100),
      trajectory_alignment_score: Math.round((accuracy - 0.1 + Math.random() * 0.2) * 100),
    },
    llmJudgeReasoning: `⚠️ **MOCK JUDGE — NOT A REAL EVALUATION** ⚠️

This score was generated by the built-in **demo/mock** judge, which does **not**
call an LLM — it returns a semi-random pass. **Do not trust this pass rate.** To
get a real verdict, set the run's judge model to a real provider (e.g. a Bedrock
model) and confirm it's invocable in your account.

---

**Mock Evaluation Result**

The agent demonstrated ${passFailStatus === 'passed' ? 'appropriate' : 'incomplete'} RCA methodology:

${hasToolCalls ? '✅ Used diagnostic tools to gather system information' : '❌ Did not use diagnostic tools'}
${hasConclusion ? '✅ Provided a clear root cause identification' : '❌ Missing clear root cause conclusion'}

**Expected Outcomes Coverage:**
${expectedOutcomes?.map((outcome, i) => `${i + 1}. "${outcome.substring(0, 50)}..." - ${Math.random() > 0.3 ? '✅ Addressed' : '⚠️ Partially addressed'}`).join('\n') || 'No expected outcomes provided'}

*Note: This is a simulated evaluation for demo purposes.*`,
    improvementStrategies: passFailStatus === 'failed' ? [
      {
        category: 'Tool Usage',
        issue: 'Insufficient diagnostic tool usage',
        recommendation: 'Consider using more diagnostic tools before drawing conclusions',
        priority: 'high'
      },
      {
        category: 'Analysis Depth',
        issue: 'Reasoning could be more detailed',
        recommendation: 'Provide more detailed reasoning connecting observations to root cause',
        priority: 'medium'
      }
    ] : []
  };
}

/**
 * GET /api/judge/openai-compatible-models
 * Discover available models from the configured OpenAI-compatible endpoint.
 * Returns { models: string[], endpoint: string, configured: boolean }
 */
router.get('/api/judge/openai-compatible-models', async (_req: Request, res: Response) => {
  const endpoint = serverConfig.OPENAI_COMPATIBLE_ENDPOINT;
  // Derive the /models URL from the chat completions endpoint
  const modelsUrl = endpoint.replace(/\/chat\/completions$/, '/models');

  debug('JudgeAPI', 'Fetching OpenAI-compatible models from:', modelsUrl);

  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (serverConfig.OPENAI_COMPATIBLE_API_KEY) {
    headers['Authorization'] = `Bearer ${serverConfig.OPENAI_COMPATIBLE_API_KEY}`;
  }

  try {
    const response = await fetch(modelsUrl, { headers });
    if (!response.ok) {
      const body = await response.text();
      return res.status(response.status).json({
        error: `OpenAI-compatible /models returned ${response.status}`,
        details: body,
        endpoint: modelsUrl,
        configured: !!serverConfig.OPENAI_COMPATIBLE_API_KEY,
      });
    }
    const data = await response.json();
    // OpenAI /models returns { object: "list", data: [{ id, ... }] }
    const models: string[] = (data.data || data.models || []).map((m: any) => m.id || m).filter(Boolean);
    debug('JudgeAPI', 'Discovered', models.length, 'OpenAI-compatible models');
    return res.json({
      models,
      endpoint: modelsUrl,
      configured: !!serverConfig.OPENAI_COMPATIBLE_API_KEY,
    });
  } catch (err: any) {
    return res.status(503).json({
      error: `Cannot reach OpenAI-compatible endpoint: ${err.message}`,
      endpoint: modelsUrl,
      configured: !!serverConfig.OPENAI_COMPATIBLE_API_KEY,
    });
  }
});

/**
 * GET /api/judge/bedrock-models
 * Discover available Anthropic models from AWS Bedrock via ListInferenceProfiles.
 * Returns { models: Array<{id, name}>, region: string, configured: boolean }
 */
router.get('/api/judge/bedrock-models', async (_req: Request, res: Response) => {
  const region = serverConfig.AWS_REGION;
  debug('JudgeAPI', 'Fetching Bedrock inference profiles from region:', region);

  try {
    const client = new BedrockClient({
      region,
      credentials: fromNodeProviderChain(),
    });

    const command = new ListInferenceProfilesCommand({});
    const response = await client.send(command);

    const profiles = response.inferenceProfileSummaries || [];
    const anthropicModels = profiles
      .filter(p => (p.inferenceProfileId || '').includes('anthropic'))
      .map(p => ({
        id: p.inferenceProfileId,
        name: p.inferenceProfileName || p.inferenceProfileId,
      }));

    debug('JudgeAPI', 'Discovered', anthropicModels.length, 'Anthropic Bedrock models');
    return res.json({
      models: anthropicModels,
      region,
      configured: true,
    });
  } catch (err: any) {
    debug('JudgeAPI', 'Bedrock discovery failed:', err.message);
    return res.status(503).json({
      error: `Cannot discover Bedrock models: ${err.message}`,
      region,
      configured: false,
    });
  }
});

/**
 * GET /api/judge/anthropic-models
 * Discover available models from the Anthropic direct API (GET /v1/models).
 * Anthropic ids (e.g. `claude-opus-4-1-20250805`) differ from the Bedrock
 * inference-profile ids and the Copilot slugs for the same model — each
 * provider names the same model differently, so discovery per provider is
 * the only reliable way to get usable ids.
 * Returns { models: Array<{id, name}>, configured: boolean }
 */
router.get('/api/judge/anthropic-models', async (_req: Request, res: Response) => {
  const configured = !!serverConfig.ANTHROPIC_API_KEY;
  const modelsUrl = `${serverConfig.ANTHROPIC_BASE_URL.replace(/\/$/, '')}/v1/models`;
  debug('JudgeAPI', 'Fetching Anthropic models from:', modelsUrl);
  if (!configured) {
    return res.status(503).json({
      error: 'Anthropic API not configured — set ANTHROPIC_API_KEY.',
      endpoint: modelsUrl,
      configured,
    });
  }
  // SSRF guard: never forward ANTHROPIC_API_KEY to a non-allowlisted host.
  const anthropicUrlError = validateDiscoveryUrl(modelsUrl, ['api.anthropic.com']);
  if (anthropicUrlError) {
    return res.status(400).json({ error: anthropicUrlError, endpoint: modelsUrl, configured });
  }
  try {
    const response = await fetch(modelsUrl, {
      headers: {
        'x-api-key': serverConfig.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
      },
    });
    if (!response.ok) {
      const body = await response.text();
      return res.status(response.status).json({
        error: `Anthropic /v1/models returned ${response.status}`,
        details: body,
        endpoint: modelsUrl,
        configured,
      });
    }
    const data = await response.json();
    // Anthropic /v1/models returns { data: [{ id, display_name, ... }] }
    const models = (data.data || []).map((m: any) => ({
      id: m.id,
      name: m.display_name || m.id,
    })).filter((m: any) => m.id);
    debug('JudgeAPI', 'Discovered', models.length, 'Anthropic models');
    return res.json({ models, endpoint: modelsUrl, configured });
  } catch (err: any) {
    return res.status(503).json({
      error: `Cannot reach Anthropic API: ${err.message}`,
      endpoint: modelsUrl,
      configured,
    });
  }
});

/**
 * GET /api/judge/github-models
 * Discover models from the GitHub Models catalog (and, by extension, the
 * Copilot model surface). Returns the vendor-prefixed ids GitHub uses
 * (e.g. `openai/gpt-4o`, `anthropic/claude-3.5-sonnet`) — these are the
 * ids you'd reference when judging via Copilot/GitHub Models, distinct from
 * the Anthropic-direct and Bedrock ids for the same underlying model.
 * Returns { models: Array<{id, name}>, configured: boolean }
 */
router.get('/api/judge/github-models', async (_req: Request, res: Response) => {
  const configured = !!serverConfig.GITHUB_TOKEN;
  const url = serverConfig.GITHUB_MODELS_URL;
  debug('JudgeAPI', 'Fetching GitHub Models catalog from:', url);
  if (!configured) {
    return res.status(503).json({
      error: 'GitHub Models not configured — set GITHUB_TOKEN (a PAT with models:read).',
      endpoint: url,
      configured,
    });
  }
  // SSRF guard: never forward GITHUB_TOKEN to a non-allowlisted host.
  const githubUrlError = validateDiscoveryUrl(url, ['models.github.ai', 'api.githubcopilot.com', 'github.com']);
  if (githubUrlError) {
    return res.status(400).json({ error: githubUrlError, endpoint: url, configured });
  }
  try {
    const response = await fetch(url, {
      headers: {
        'Authorization': `Bearer ${serverConfig.GITHUB_TOKEN}`,
        'Accept': 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
    });
    if (!response.ok) {
      const body = await response.text();
      return res.status(response.status).json({
        error: `GitHub Models catalog returned ${response.status}`,
        details: body,
        endpoint: url,
        configured,
      });
    }
    const data = await response.json();
    // GitHub Models catalog returns an array of { id, name, publisher, ... }
    // (older shape) or { models: [...] }. Handle both.
    const list: any[] = Array.isArray(data) ? data : (data.models || data.data || []);
    const models = list.map((m: any) => ({
      id: m.id || m.name,
      name: m.friendly_name || m.name || m.id,
    })).filter((m: any) => m.id);
    debug('JudgeAPI', 'Discovered', models.length, 'GitHub Models');
    return res.json({ models, endpoint: url, configured });
  } catch (err: any) {
    return res.status(503).json({
      error: `Cannot reach GitHub Models catalog: ${err.message}`,
      endpoint: url,
      configured,
    });
  }
});

/**
 * POST /api/judge - Evaluate agent trajectory
 */
router.post('/api/judge', async (req: Request, res: Response) => {
  try {
    const { trajectory, expectedOutcomes, expectedTrajectory, logs, modelId, evaluatorId, runId, agents, evidenceContext } = req.body;

    // Validate required fields
    if (!trajectory || !Array.isArray(trajectory) || trajectory.length === 0) {
      return res.status(400).json({
        error: 'Trajectory is required and must be a non-empty array'
      });
    }

    if (!expectedOutcomes?.length && !expectedTrajectory?.length) {
      return res.status(400).json({
        error: 'Missing required field: expectedOutcomes or expectedTrajectory'
      });
    }

    // Load evaluator if specified, otherwise use default
    let evaluator: Evaluator;
    if (evaluatorId) {
      debug('JudgeAPI', 'Loading evaluator:', evaluatorId);
      // Check system evaluators first (they aren't stored in the storage backend)
      if (isSystemEvaluatorId(evaluatorId)) {
        const systemEval = getSystemEvaluatorById(evaluatorId);
        if (!systemEval) {
          return res.status(400).json({
            error: `System evaluator not found: ${evaluatorId}`
          });
        }
        evaluator = systemEval;
      } else {
        const storage = getStorageModule();
        const loadedEvaluator = await storage.evaluators.getById(evaluatorId);
        if (!loadedEvaluator) {
          return res.status(400).json({
            error: `Evaluator not found: ${evaluatorId}`
          });
        }
        evaluator = loadedEvaluator;
      }
    } else {
      debug('JudgeAPI', 'Using default evaluator (backward compatible)');
      evaluator = getDefaultEvaluator();
    }

    // Determine provider from evaluator's inferenceConfig or model config
    // Priority: evaluator.inferenceConfig.provider > modelConfig.provider > 'bedrock'
    const config = loadConfigSync();
    let modelConfig = config.models[modelId];
    if (!modelConfig) {
      // Try to find by model_id (in case full Bedrock ID was passed)
      modelConfig = Object.values(config.models).find(m => m.model_id === modelId);
    }
    const provider = evaluator.inferenceConfig?.provider || modelConfig?.provider || 'bedrock';

    // Use the resolved model_id: evaluator override > config > provided
    const resolvedModelId = evaluator.inferenceConfig?.modelId || modelConfig?.model_id || modelId;
    debug('JudgeAPI', 'Using provider:', provider, 'model:', resolvedModelId, 'evaluator:', evaluator.name);

    // Route to appropriate provider
    if (provider === 'demo') {
      // Loud, always-on warning (not behind the debug flag): the mock judge
      // returns a semi-random pass without calling an LLM, so a run can look
      // like "100% pass" while nothing was actually judged. Make that
      // impossible to miss in the server logs.
      console.warn(
        '\u26a0\ufe0f  [agent-health] MOCK JUDGE IN USE: judge model "%s" resolves to the "demo" provider — ' +
        'scores are NOT real (no LLM is called). Pin a real judge model (e.g. --judge-model <bedrock-id> ' +
        'or evaluator.inferenceConfig) to get a real verdict.',
        resolvedModelId
      );
      debug('JudgeAPI', 'Demo provider - returning mock evaluation');
      const mockResult = generateMockEvaluation(trajectory, expectedOutcomes);
      return res.json(mockResult);
    }

    if (provider === 'claude-code') {
      debug('JudgeAPI', 'Claude Code provider - spawning claude CLI');
      // Pass the resolved evaluator so its `systemPrompt` replaces the
      // hardcoded baseline (and `scoringConfig.metrics` drives dynamic metric
      // extraction). Pre-fix this was the silent-prompt-drop bug.
      const result = await evaluateWithClaudeCode(
        { trajectory, expectedOutcomes, expectedTrajectory, logs },
        evaluator
      );
      return res.json(result);
    }

    if (provider === 'pi') {
      debug('JudgeAPI', 'Pi provider - spawning pi CLI');
      // Pass the resolved evaluator so its `systemPrompt` is forwarded to
      // the pi CLI via `--system-prompt` instead of the hardcoded baseline.
      const result = await evaluateWithPi(
        { trajectory, expectedOutcomes, expectedTrajectory, logs },
        evaluator
      );
      return res.json(result);
    }

    if (provider === 'agent') {
      // Evidence agent judge: complete trajectory/testcase files are always
      // available through restricted in-process bash. A runId may discover a
      // file-mode canonical mount or enable cluster-mode query tools.
      // Defense in depth against cross-run/cross-tenant exfiltration: the trace
      // tools will happily read spans/logs for whatever runId they're given, so
      // a direct caller could pass a benign trajectory but a *different* run's
      // runId and leak that run's data through the judge's reasoning text. Bind
      // the runId to the trajectory the request also carries: when the
      // trajectory steps carry runId(s) (the SDK path always derives runId from
      // the judged result, so they match), the requested runId MUST be one of
      // them. When the trajectory carries no runId we cannot corroborate it —
      // this provider then trusts the caller and is single-tenant-only (see
      // AGENTS.md "Trace correlation"; gate it behind auth in shared clusters).
      const trajectoryRunIds = new Set(
        (trajectory as any[])
          .map((s) => s?.runId)
          .filter((id): id is string => typeof id === 'string' && id.length > 0)
      );
      if (runId && trajectoryRunIds.size > 0 && !trajectoryRunIds.has(runId)) {
        return res.status(403).json({
          error:
            'runId does not match the submitted trajectory — the agent (trace) judge ' +
            'may only inspect the run that produced its trajectory',
        });
      }
      let trustedAgentKey: string | undefined;
      if (runId) {
        const storage = getStorageModule();
        const runRecord = await storage.evaluationRuns.getById(runId);
        const reportRecord = runRecord ? null : await storage.runs.getById(runId);
        trustedAgentKey = runRecord?.agentKey || reportRecord?.agentKey;
        const requestedAgentKey = evidenceContext?.agentKey;
        if (requestedAgentKey && trustedAgentKey && requestedAgentKey !== trustedAgentKey) {
          return res.status(403).json({ error: 'agentKey does not match the stored run metadata' });
        }
      }
      debug('JudgeAPI', 'Agent evidence judge - evaluating with restricted bash (runId=' + (runId || 'none') + ')');
      // Pass the resolved evaluator so a saved `systemPrompt` replaces the
      // default base prompt (the runtime evidence/tool addendum is still
      // appended inside the service and describes only actual state).
      const result = await evaluateWithPiAgenticTrace(
        {
          trajectory,
          expectedOutcomes,
          expectedTrajectory,
          logs,
          runId,
          modelId: resolvedModelId,
          agents,
          evidenceContext: evidenceContext && typeof evidenceContext === 'object'
            ? {
                ...evidenceContext,
                agentKey: trustedAgentKey,
                // HTTP clients control evidenceContext metadata, so never
                // accept a workspace path from it. Only the server-owned agent
                // configuration may select files for an API-triggered judge.
                // In-process evaluation still uses the connector's actual
                // per-run workspace because that metadata never crosses this
                // untrusted request boundary.
                workspaceDir: (() => {
                  const cwd = config.agents.find(
                    (agent) => agent.key === trustedAgentKey
                  )?.connectorConfig?.cwd;
                  return typeof cwd === 'string' && cwd.trim() ? cwd : undefined;
                })(),
              }
            : undefined,
          keepEvidence: config.judge?.keepEvidence === true,
        },
        evaluator
      );
      return res.json(result);
    }

    if (provider === 'agentic') {
      debug('JudgeAPI', 'Agentic judge provider - running agent-based evaluation');
      const judgeConfig = config.judge || {};
      const backend = resolvedModelId === 'agentic-custom' ? 'custom' : 'claude-code';
      // Pass the resolved evaluator so its `systemPrompt` replaces the
      // baseline (the AGENTIC_JUDGE_ADDENDUM stays appended).
      const result = await evaluateWithAgenticJudge(
        { trajectory, expectedOutcomes, expectedTrajectory, logs, runId },
        {
          backend,
          endpoint: judgeConfig.endpoint,
        },
        evaluator
      );
      return res.json(result);
    }

    if (provider === 'openai-compatible') {
      debug('JudgeAPI', 'OpenAI-compatible provider - calling endpoint');
      const result = await evaluateWithOpenAICompatible(
        { trajectory, expectedOutcomes, expectedTrajectory, logs },
        resolvedModelId,
        evaluator
      );
      return res.json(result);
    }

    if (provider === 'litellm') {
      debug('JudgeAPI', 'LiteLLM provider - calling OpenAI-compatible endpoint');
      const result = await evaluateWithLiteLLM(
        { trajectory, expectedOutcomes, expectedTrajectory, logs },
        resolvedModelId,
        evaluator
      );
      return res.json(result);
    }

    // Default: bedrock
    const result = await evaluateTrajectory({
      trajectory,
      expectedOutcomes,
      expectedTrajectory,
      logs
    }, resolvedModelId, evaluator);

    res.json(result);

  } catch (error: any) {
    console.error('[JudgeAPI] Error during evaluation:', error);

    const provider = (() => {
      try {
        const config = loadConfigSync();
        const { modelId } = req.body;
        const modelConfig = config.models[modelId] ||
          Object.values(config.models).find(m => m.model_id === modelId);
        return modelConfig?.provider || 'bedrock';
      } catch {
        return 'bedrock';
      }
    })();

    const errorMessage = provider === 'agentic'
      ? parseAgenticJudgeError(error)
      : provider === 'pi' || provider === 'agent'
        ? parsePiError(error)
        : provider === 'claude-code'
          ? parseClaudeCodeError(error)
          : provider === 'litellm'
            ? parseLiteLLMError(error)
            : provider === 'openai-compatible'
              ? parseOpenAICompatibleError(error)
              : parseBedrockError(error);

    res.status(500).json({
      error: `Judge evaluation failed: ${errorMessage}`,
      details: error.message
    });
  }
});

export default router;
